---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    field.cattle.io/creatorId: user-jsrd9
    field.cattle.io/publicEndpoints: '[{"nodeName":"c-bstp9:m-c6b36ffbca41","addresses":["195.201.196.53"],"port":6767,"protocol":"TCP","podName":"bazarr:bazarr-6db9f97bc-cgm8r","allNodes":false}]'
  creationTimestamp: "2020-05-16T15:41:11Z"
  generation: 5
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-bazarr-bazarr
  name: bazarr
  namespace: bazarr
  resourceVersion: "32190"
  selfLink: /apis/apps/v1/namespaces/bazarr/deployments/bazarr
  uid: 31e0a526-f993-4eca-abee-4efc64f48305
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-bazarr-bazarr
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-05-16T15:41:13Z"
        field.cattle.io/ports: '[[{"containerPort":6767,"dnsName":"bazarr-hostport","hostPort":6767,"kind":"HostPort","name":"6767tcp67670","protocol":"TCP","sourcePort":6767}]]'
        fluxcd.io/automated: "true"
      creationTimestamp:
      labels:
        workload.user.cattle.io/workloadselector: deployment-bazarr-bazarr
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: Europe/London
        image: linuxserver/bazarr:latest
        imagePullPolicy: Always
        name: bazarr
        ports:
        - containerPort: 6767
          hostPort: 6767
          name: 6767tcp6767
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /mnt
          name: vol1
        - mountPath: /config
          name: vol2
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /mnt
          type: ""
        name: vol1
      - hostPath:
          path: /opt/appdata/bazarr
          type: ""
        name: vol2
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-05-16T15:43:36Z"
    lastUpdateTime: "2020-05-16T15:43:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-05-16T15:41:11Z"
    lastUpdateTime: "2020-05-16T15:43:36Z"
    message: ReplicaSet "bazarr-6db9f97bc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
