apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: user-gj778
    field.cattle.io/ingressState: '{"cmFkYXJycHQvcmFkYXJyL3JhZGFycnB0LmJsYWNrZHJhZ29uLnR2Ly83ODc4":"deployment:radarr:radarrpt"}'
    field.cattle.io/publicEndpoints: '[{"addresses":["195.201.196.53"],"port":443,"protocol":"HTTPS","serviceName":"radarr:ingress-bedceec656f5630679079b0a25e6187c","ingressName":"radarr:radarrpt","hostname":"radarrpt.blackdragon.tv","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
  name: radarrpt
  selfLink: /apis/extensions/v1beta1/namespaces/radarr/ingresses/radarrpt
spec:
  rules:
  - host: radarrpt.blackdragon.tv
    http:
      paths:
      - backend:
          serviceName: ingress-bedceec656f5630679079b0a25e6187c
          servicePort: 7878
  tls:
  - hosts:
    - radarrpt.blackdragon.tv
status:
  loadBalancer: {}
