apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-gj778
    field.cattle.io/publicEndpoints: '[{"nodeName":"c-jcwbl:m-c6b36ffbca41","addresses":["195.201.196.53"],"port":6767,"protocol":"TCP","podName":"bazarr:bazarrpt-79b58dc57d-md9x5","allNodes":false}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-bazarr-bazarrpt
  name: bazarrpt
  selfLink: /apis/apps/v1/namespaces/bazarr/deployments/bazarrpt
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-bazarr-bazarrpt
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-05-27T22:29:10Z"
        field.cattle.io/ports: '[[{"containerPort":6767,"dnsName":"bazarrpt-hostport","hostPort":6767,"kind":"HostPort","name":"6767tcp67670","protocol":"TCP","sourcePort":6767}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-bazarr-bazarrpt
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: Europe/London
        image: linuxserver/bazarr:development
        imagePullPolicy: Always
        name: bazarrpt
        ports:
        - containerPort: 6767
          hostPort: 6767
          name: 6767tcp67670
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /config
          name: vol1
        - mountPath: /mnt
          name: vol2
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /opt/appdata/bazarr/
          type: ""
        name: vol1
      - hostPath:
          path: /mnt
          type: ""
        name: vol2
status: {}
