apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-gj778
    field.cattle.io/publicEndpoints: '[{"nodeName":"c-jcwbl:m-c6b36ffbca41","addresses":["195.201.196.53"],"port":3000,"protocol":"TCP","podName":"flood-ui:flood-ui-65479d7f54-kf6bm","allNodes":false}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-flood-ui-flood-ui
  name: flood-ui
  selfLink: /apis/apps/v1/namespaces/flood-ui/deployments/flood-ui
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-flood-ui-flood-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-05-28T12:03:28Z"
        field.cattle.io/ports: '[[{"containerPort":3000,"dnsName":"flood-ui-hostport","hostPort":3000,"kind":"HostPort","name":"3000tcp30000","protocol":"TCP","sourcePort":3000}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-flood-ui-flood-ui
    spec:
      containers:
      - image: jfurrow/flood-ui:latest
        imagePullPolicy: Always
        name: flood-ui
        ports:
        - containerPort: 3000
          hostPort: 3000
          name: 3000tcp30000
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data
          name: vol1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /opt/appdata/flood-ui
          type: ""
        name: vol1
status: {}
