apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    field.cattle.io/creatorId: user-gj778
    field.cattle.io/publicEndpoints: '[{"addresses":["195.201.196.53"],"port":443,"protocol":"HTTPS","serviceName":"radarr:ingress-bedceec656f5630679079b0a25e6187c","ingressName":"radarr:radarrpt","hostname":"radarrpt.blackdragon.tv","allNodes":true},{"addresses":["195.201.196.53"],"port":32376,"protocol":"TCP","serviceName":"radarr:radarrpt-nodeport","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-radarr-radarrpt
  name: radarrpt
  selfLink: /apis/apps/v1/namespaces/radarr/deployments/radarrpt
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-radarr-radarrpt
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-05-27T21:40:23Z"
        field.cattle.io/ports: '[[{"containerPort":7878,"dnsName":"radarrpt-nodeport","hostPort":0,"kind":"NodePort","name":"7878tcp01","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-radarr-radarrpt
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: Europe/London
        image: linuxserver/radarr:preview
        imagePullPolicy: Always
        name: radarrpt
        ports:
        - containerPort: 7878
          name: 7878tcp01
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /config
          name: vol1
        - mountPath: /config_mp4_automator
          name: vol2
        - mountPath: /mnt
          name: vol3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /opt/appdata/radarrpt
          type: ""
        name: vol1
      - hostPath:
          path: /opt/appdata/radarr/mp4_automator
          type: ""
        name: vol2
      - hostPath:
          path: /mnt
          type: ""
        name: vol3
status: {}
