apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    field.cattle.io/creatorId: user-gj778
    field.cattle.io/publicEndpoints: '[{"addresses":["195.201.196.53"],"port":31498,"protocol":"TCP","serviceName":"sonarr:sonarrfr-nodeport","allNodes":true},{"addresses":["195.201.196.53"],"port":443,"protocol":"HTTPS","serviceName":"sonarr:ingress-f908a4dc0ac518c6011d7601abd57651","ingressName":"sonarr:sonarrfr","hostname":"sonarrfr.blackdragon.tv","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-sonarr-sonarrfr
  name: sonarrfr
  selfLink: /apis/apps/v1/namespaces/sonarr/deployments/sonarrfr
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-sonarr-sonarrfr
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-05-27T21:38:27Z"
        field.cattle.io/ports: '[[{"containerPort":8989,"dnsName":"sonarrfr-nodeport","hostPort":0,"kind":"NodePort","name":"8989tcp01","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-sonarr-sonarrfr
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: Europe/London
        image: linuxserver/sonarr:preview
        imagePullPolicy: Always
        name: sonarrfr
        ports:
        - containerPort: 8989
          name: 8989tcp01
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /config
          name: vol1
        - mountPath: /config_mp4_automator
          name: vol2
        - mountPath: /mnt
          name: vol3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /opt/appdata/sonarr
          type: ""
        name: vol1
      - hostPath:
          path: /opt/appdata/sonarr/mp4_automator
          type: ""
        name: vol2
      - hostPath:
          path: /mnt
          type: ""
        name: vol3
status: {}
