apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    field.cattle.io/creatorId: user-gj778
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-unpackerr-unpackerrpt
  name: unpackerrpt
  selfLink: /apis/apps/v1/namespaces/unpackerr/deployments/unpackerrpt
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-unpackerr-unpackerrpt
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-05-27T22:21:20Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-unpackerr-unpackerrpt
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: Etc/UTC
        - name: UN_RADARR_0_API_KEY
          value: a5319aa57d3a44cd80ea3f0da4b456aa
        - name: UN_RADARR_0_URL
          value: http://195.201.196.53:32376
        image: hotio/unpackerr:latest
        imagePullPolicy: Always
        name: unpackerrpt
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /config
          name: vol1
        - mountPath: /downloads
          name: vol2
        - mountPath: /mnt
          name: vol3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /opt/appdata/unpackerr/
          type: ""
        name: vol1
      - hostPath:
          path: /mnt
          type: ""
        name: vol2
      - hostPath:
          path: /mnt
          type: ""
        name: vol3
status: {}
